#!/bin/bash
# jira-daily-setup.sh — Interactive launchd installer for /jira-daily
#
# Sets up a per-user macOS LaunchAgent that runs `/jira-daily` headlessly
# at user-specified times (typically twice a day). Detects user environment
# (HOME, node path, working directory) and generates a personalized plist.
#
# Prereqs:
#   - macOS
#   - Claude Code CLI installed (`claude`)
#   - Homebrew + terminal-notifier (this script offers to install if missing)
#   - Jira MCP server configured in your Claude Code settings
#   - The /jira-daily slash command installed (run Agcoco install.sh first)
#
# Usage: bash jira-daily-setup.sh

set -e

# ─── colors ───────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[✗]${NC} $1" >&2; }
ask()   { echo -en "${BOLD}?${NC} $1"; }

echo ""
echo "════════════════════════════════════════════════"
echo " /jira-daily 자동 스케줄 설치 (macOS launchd)"
echo "════════════════════════════════════════════════"
echo ""

# ─── 1. OS check ──────────────────────────────────────────
if [[ "$(uname)" != "Darwin" ]]; then
    error "이 스크립트는 macOS 전용입니다."
    exit 1
fi
info "macOS 확인"

# ─── 2. claude CLI check ──────────────────────────────────
if ! command -v claude >/dev/null 2>&1; then
    error "claude CLI가 설치되어 있지 않습니다. https://claude.com/claude-code 참고."
    exit 1
fi
CLAUDE_PATH=$(command -v claude)
info "claude CLI 발견: $CLAUDE_PATH"

# node가 들어있는 디렉토리 추출 (claude는 보통 nvm 경로의 node 옆에 있음)
NODE_BIN_DIR=$(dirname "$CLAUDE_PATH")
info "node bin 디렉토리: $NODE_BIN_DIR"

# ─── 3. /jira-daily 명령어 설치 확인 ───────────────────────
if [[ ! -f "$HOME/.claude/commands/jira-daily.md" ]]; then
    error "/jira-daily 슬래시 커맨드가 없습니다."
    error "Agcoco install.sh 를 먼저 실행해주세요:"
    error "  cd ~/personal/Agcoco && ./install.sh"
    exit 1
fi
info "/jira-daily 슬래시 커맨드 확인"

# ─── 4. terminal-notifier check ───────────────────────────
if ! command -v terminal-notifier >/dev/null 2>&1; then
    warn "terminal-notifier 미설치 (알림 클릭 액션에 필요)"
    if ! command -v brew >/dev/null 2>&1; then
        error "Homebrew도 없어서 자동 설치 불가. 직접 설치해주세요:"
        error "  https://brew.sh"
        exit 1
    fi
    ask "지금 brew install terminal-notifier 실행할까요? [y/N] "
    read -r ans
    if [[ "$ans" =~ ^[Yy]$ ]]; then
        brew install terminal-notifier
    else
        warn "건너뜀. 나중에 직접 설치하세요: brew install terminal-notifier"
    fi
else
    info "terminal-notifier 확인"
fi

# ─── 5. 작업 디렉토리 ──────────────────────────────────────
DEFAULT_WORKDIR="$HOME/workspace/mailwork"
[[ ! -d "$DEFAULT_WORKDIR" ]] && DEFAULT_WORKDIR="$PWD"

echo ""
ask "작업 디렉토리는? (계획서가 저장될 .plans/의 부모) [기본: $DEFAULT_WORKDIR]: "
read -r WORKDIR
WORKDIR="${WORKDIR:-$DEFAULT_WORKDIR}"
WORKDIR="${WORKDIR/#\~/$HOME}"

if [[ ! -d "$WORKDIR" ]]; then
    error "디렉토리가 없습니다: $WORKDIR"
    exit 1
fi
info "작업 디렉토리: $WORKDIR"
info "계획서 저장 위치: $WORKDIR/.plans/"
mkdir -p "$WORKDIR/.plans"

# ─── 6. 스케줄 시간 ────────────────────────────────────────
echo ""
echo "스케줄 시간을 24시간 형식으로 입력하세요 (HH:MM, 평일만 발화)."
echo "여러 시간은 쉼표로 구분 (예: 08:30,13:30)."
ask "시간 [기본: 08:30,13:30]: "
read -r TIMES_INPUT
TIMES_INPUT="${TIMES_INPUT:-08:30,13:30}"

# 파싱: "HH:MM,HH:MM" → "HH MM" 라인들
SCHEDULE_DICTS=""
IFS=',' read -ra TIMES <<< "$TIMES_INPUT"
for t in "${TIMES[@]}"; do
    t="${t// /}"
    if [[ ! "$t" =~ ^([0-9]{1,2}):([0-9]{2})$ ]]; then
        error "잘못된 시간 형식: $t (HH:MM 이어야 함)"
        exit 1
    fi
    HOUR="${BASH_REMATCH[1]}"
    MIN="${BASH_REMATCH[2]}"
    if (( HOUR < 0 || HOUR > 23 || MIN < 0 || MIN > 59 )); then
        error "시간 범위 오류: $t"
        exit 1
    fi
    for WD in 1 2 3 4 5; do
        SCHEDULE_DICTS+="        <dict><key>Weekday</key><integer>${WD}</integer><key>Hour</key><integer>${HOUR}</integer><key>Minute</key><integer>${MIN}</integer></dict>
"
    done
done
info "스케줄: $TIMES_INPUT (평일 월-금)"

# ─── 7. Label / paths ─────────────────────────────────────
USER_NAME=$(id -un)
LABEL="com.${USER_NAME}.jira-daily"
SCRIPT_DIR="$HOME/.claude/scripts"
LOG_DIR="$HOME/.claude/logs"
WRAPPER="$SCRIPT_DIR/jira-daily.sh"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"

mkdir -p "$SCRIPT_DIR" "$LOG_DIR" "$(dirname "$PLIST")"

# ─── 8. 기존 등록 확인 ─────────────────────────────────────
if launchctl print "gui/$(id -u)/${LABEL}" >/dev/null 2>&1; then
    warn "기존 LaunchAgent가 이미 등록돼 있음: $LABEL"
    ask "재등록할까요? (기존 unload 후 새로 load) [Y/n] "
    read -r ans
    if [[ "$ans" =~ ^[Nn]$ ]]; then
        info "취소됨"
        exit 0
    fi
    launchctl bootout "gui/$(id -u)/${LABEL}" 2>/dev/null || true
    info "기존 등록 해제"
fi

# ─── 9. wrapper script 생성 ────────────────────────────────
cat > "$WRAPPER" <<EOF
#!/bin/bash
# Auto-generated by jira-daily-setup.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Triggered by launchd: ${LABEL}

set -e

export PATH="${NODE_BIN_DIR}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
export HOME="${HOME}"
export JIRA_DAILY_PLANS_DIR="${WORKDIR}/.plans"

LOG_DIR="${LOG_DIR}"
mkdir -p "\$LOG_DIR"

cd "${WORKDIR}"

{
  echo ""
  echo "===== \$(date '+%Y-%m-%d %H:%M:%S %Z') jira-daily start ====="
} >> "\$LOG_DIR/jira-daily.log"

claude --dangerously-skip-permissions -p "/jira-daily" \\
  >> "\$LOG_DIR/jira-daily.log" \\
  2>> "\$LOG_DIR/jira-daily.err"

echo "===== \$(date '+%Y-%m-%d %H:%M:%S %Z') jira-daily end =====" >> "\$LOG_DIR/jira-daily.log"
EOF
chmod +x "$WRAPPER"
info "wrapper 생성: $WRAPPER"

# ─── 10. plist 생성 ────────────────────────────────────────
cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${WRAPPER}</string>
    </array>

    <key>StartCalendarInterval</key>
    <array>
${SCHEDULE_DICTS}    </array>

    <key>StandardOutPath</key>
    <string>${LOG_DIR}/jira-daily.launchd.log</string>

    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/jira-daily.launchd.err</string>

    <key>RunAtLoad</key>
    <false/>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>${NODE_BIN_DIR}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
        <key>HOME</key>
        <string>${HOME}</string>
        <key>JIRA_DAILY_PLANS_DIR</key>
        <string>${WORKDIR}/.plans</string>
    </dict>
</dict>
</plist>
EOF
info "plist 생성: $PLIST"

if ! plutil -lint "$PLIST" >/dev/null; then
    error "plist 검증 실패. $PLIST 확인 필요"
    exit 1
fi

# ─── 11. launchd 등록 ──────────────────────────────────────
launchctl bootstrap "gui/$(id -u)" "$PLIST"
info "launchd 등록 완료"

# ─── 12. 안내 ─────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════"
echo " ${GREEN}설치 완료${NC}"
echo "════════════════════════════════════════════════"
echo ""
echo "스케줄: ${BOLD}평일 ${TIMES_INPUT}${NC}"
echo "작업 디렉토리: $WORKDIR"
echo "계획서: $WORKDIR/.plans/"
echo "로그: $LOG_DIR/jira-daily.{log,err,launchd.{log,err}}"
echo ""
echo "운영 명령:"
echo "  지금 즉시 실행 (테스트): launchctl kickstart -k gui/\$(id -u)/${LABEL}"
echo "  상태 확인:               launchctl print gui/\$(id -u)/${LABEL}"
echo "  스케줄 해제:             launchctl bootout gui/\$(id -u)/${LABEL}"
echo "  수동 실행:               Claude Code에서 /jira-daily"
echo ""
warn "첫 실행 시 macOS가 알림 권한을 물을 수 있습니다. 허용해주세요."
warn "Mac이 잠자기 중이면 발화 안 됨 (켜지면 catch-up 시도)."
echo ""

ask "지금 한 번 테스트 실행할까요? [Y/n] "
read -r ans
if [[ ! "$ans" =~ ^[Nn]$ ]]; then
    launchctl kickstart -k "gui/$(id -u)/${LABEL}"
    info "kickstart 전송. 수 초 후 알림 확인"
    info "로그 모니터링: tail -f $LOG_DIR/jira-daily.log"
fi
